### ISSUE TITLE
Application hangs... but nothing tells user if it's a bug or if something is done in background

### ISSUE THREAD

**Issue by pseudo555** [CamelCaseName/HousePartyTranslator#57]
Classical GUI issue:
When application is doing heavy stuff in background, the HMI must not freeze. Instead a please wait with finite or infinite progress bar/loop should be display so the user know (s)he has to wait until completion.

Got that by clicking on Auto or Open storyExplorer, after loading the originalStory.story file.

**Comment by CamelCaseName** [comment]
Yeah i know, i should offload it to another thread. But it is such multithreaded that it will even hang everything. It only has to be run once though. I'll make the UI more clear and decoupled more

**Comment by CamelCaseName** [comment]
https://github.com/CamelCaseName/HousePartyTranslator/releases/tag/0.542
