### ISSUE TITLE
Closing application doesn't kill the process

### ISSUE THREAD

**Issue by pseudo555** [CamelCaseName/HousePartyTranslator#58]
I guess, some created thread are not Daemon, but onventionnal thread.
Thus, when the main interface is closed, all the non-daemon thread are kept alive, until completion.

Reproduction step :
1. start app
2. Click on either open/auto storyExplorer, load the originalstory.story file
3. Close the application as it seems to have frozzen

Observed behavior:
Main GUI is closed, but application still eats a lot of CPU in background.

**Comment by CamelCaseName** [comment]
Yeah this is due to the use of `Parallel.For`, need to investigate how to terminate that nicely

**Comment by CamelCaseName** [comment]
https://github.com/CamelCaseName/HousePartyTranslator/releases/tag/0.542
